.libPaths("C:/R_packages")

library(data.table)
library(jsonlite)
library(httr)
library(leaflet)
library(dplyr)
library(magrittr)
library(cartography)
library(rgeos)
library(raster)
library(mapview)
library(rgdal)
library(deldir)
library(tidyr)
library(spatstat)
library(igraph)
#devtools::install_github('bhaskarvk/leaflet.extras')